### PR TITLE
#Community Guide page updated

### PR DESCRIPTION
**Pull request by adinh808**
As per Issue [#5452](https://github.com/odpi/egeria/issues/5452), Community Page is updated with latest egeria top level README data.

### CODE REVIEW

**Review by cmgrote — CHANGES_REQUESTED** [review]
Hi @adinh808 -- thanks for the updates!

I've just reviewed them, and most of what's been added to the table is already there on the page just above the table: i.e. the calendar indicating on which day each meeting occurs, with what frequency, and with the connectivity details when you click on any of them (web links + phone numbers).  It seems to me this is both richer information, as well as something that we are more likely to keep updated simply by virtue of keeping that calendar updated -- without needing to update the contents of this page directly should we decide to add other meetings, cancel particular instances at short notice, or change the days or frequency of the meetings.  I'd therefore prefer not to include things like "every X day" as text on the page -- it's duplicative, reduces maintainability (particularly with embedded HTML inside the Markdown), and from a consumption perspective reduces the conciseness of the information that's already available on the page (via the calendar directly above).

The one exception to this I see is that you've linked the TSC home page, which indeed would be good to retain.  Could you please update the changes to just retain this link to the TSC home page?

**Comment by adinh808** [comment]
Thanks for the review. I have updated the change. I have added them as they were pointing to another website (https://lists.lfaidata.foundation/g/egeria-technical-discuss/calendar). So now jut just included only TSC homepage as you requested.

**Comment by planetf1** [comment]
Unfortunately I think this well-intended change, based off a real issue in the docs as they were, has been superceeded by the recent refactoring (which is still continuing) of the egeria docs.

For example https://odpi.github.io/egeria-docs/guides/community/ now includes all the information being discussed here, including the calendar and reference to TSC call.

As such I would recommend abandoning this change.

**Review by planetf1 — CHANGES_REQUESTED** [review]
I think this is superceeded by doc refactoring

**Comment by cmgrote** [comment]
> Thanks for the review. I have updated the change. I have added them as they were pointing to another website (https://lists.lfaidata.foundation/g/egeria-technical-discuss/calendar). So now jut just included only TSC homepage as you requested.

Sorry, indeed it isn't obvious but the Google calendar that's embedded is actually just a rendering utility for the published iCal feed from our actual calendar management site (which doesn't offer it's own mechanism of embedding a rendered view of the calendar).

Looking better -- can you also:

- put the TSC link directly against the existing "Technical Steering Committee (TSC)" wording (rather than repeating basically the same words again just to put the link against -- something we're far too guilty of doing everywhere in our docs, but I'm doing my best to cleanup as I go!)
- remove the embedded `<ul><li>` HTML as well: no need for bulleted lists as there's only a single line of content for each cell now

**Comment by adinh808** [comment]
Done. Updated as per requested changes.

**Review by cmgrote — APPROVED** [review]
Thanks for your patience with all the back-and-forth, I think we're there 👍

**Pull request merged**
